{% set name = "pymdi" %}
{% set version = "1.4.38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MolSSI/MDI_Library/archive/v{{ version }}.tar.gz
  sha256: df18a6425ef2e61e2bf8670560bd8d49dd4a858dfd727bb65b2280c5568339b4

build:
  number: 0
  skip: true  # [win and mpi != 'nompi']
  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ mpi_prefix }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake >=3.13
    - make
    - ninja
  host:
    - python
    - {{ mpi }}  # [mpi != 'nompi']
  run:
    - python
    - {{ mpi }}  # [mpi != 'nompi']

test:
  imports:
    - mdi

about:
  home: https://github.com/MolSSI/MDI_Library
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library that enables code interoperability via the MolSSI Driver Interface.
  description: |
    MDI is an effort of The MolSSI <https://molssi.org/> to improve
    and standardize the process of interoperating codes within the
    computational molecular sciences domain.  It supports fast inter-code
    communication using both the TCP/IP and MPI methods.
  doc_url: https://molssi.github.io/MDI_Library/html/index.html
  dev_url: https://github.com/MolSSI/MDI_Library

extra:
  recipe-maintainers:
    - taylor-a-barnes
