travis:
  secure:
    BINSTAR_TOKEN: Dj5pexxi5KeaWdrmZx2OH68NSUqRZtItplZ/D7znHFv1vz15iXqtFOOxb8Kz9Hogcsi5XYjBPn18UJ03mooIgKOwxil4rVj1yXxNd9Qf4PLGnKlTejkgnYcau8z28+QOV4UxUUQW+AnkfG3PgmrRj4NK38zsm83LNwJ4Kc0aKuF3q8g7C32BAE/IPrPx7DlBLY46WKU7KrZIrZZufr565d12NrC/uGGyv0A3Mc443LF5EQAKdqGGEr4bXby9438HoHvc3J3MOpPFB/FJSNJDoiLIW0/rC6yQBllVlb3ykNO4Xaaox6x4rnjF1hfZZJtA2URbh520mUUI3UaHKPEAmemMOTYsn9sWj4WWM5ZAIrkAv/Bzmksk/s8Nty+GSKgzWZov/o/WqwVIDgUGLWc8c/SIkn464LjQJK60nRdkKOutiIN/GbRUiJ9a3md/PUhNOKK4zbkozq2DZMm+SPp6R2AQzYLUoHniMZXEVHYWQhjlbpJ3zVSO00HElhYpB1jvXgIe3ztPLEO1/vkZNcUL/YO7bCgLB+PkKgvmwSPE9HZl1UKA8NPu5eNbYKcfDU9r9CoicZOX8De7+qqPpF1oMMvWA2qHxQbY20kkzt7hUj6PxbIrCFhc+pgXjhZ+g/lla2NQ0D4Dev3LX3B3dsywjma1RigiRdeKWbruRBf733E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
